### ISSUE TITLE
error compile

### ISSUE THREAD

**Issue by Roni28** [dycodex/Simple-LoRa-Gateway#1]
ada error ketika saya memasukkan script "make".
Bagaimana cara mengeatasinya ?

pi@raspberrypi:~/Simple-LoRa-Gateway $ make
g++ -DRASPBERRY_PI -DBCM2835_NO_DELAY_COMPATIBILITY -D__BASEFILE__=\"Mqtt\" -std=c++11 -c -I./deps/RadioHead src/Mqtt.cpp
In file included from src/Mqtt.cpp:3:0:
src/Mqtt.h:4:25: fatal error: mosquittopp.h: No such file or directory
 #include <mosquittopp.h>
                         ^
compilation terminated.
Makefile:38: recipe for target 'Mqtt.o' failed
make: *** [Mqtt.o] Error 1

**Comment by alwint3r** [comment]
Sorry telat banget respon nya.

Error nya disebabkan karena library client mosquitto (MQTT) nya belum diinstall.
Coba install library nya terlebih dahulu.

```
sudo apt install libmosquitto-dev libmosquittopp-dev libmosquitto1 libmosquittopp1
```
Setelah itu baru coba compile lagi code nya.
